version: "3.9"

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=x1

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    restart: always
#    ports:
#      - "5050:80"
#    volumes:
#      - ~/.pgadmin/data:/var/lib/pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@mindshift.co.kr
#      - PGADMIN_DEFAULT_PASSWORD=1234
#    depends_on:
#      - postgres
